# Summary: Aggregates and imports all service modules for NixOS configuration.
{ ... }:
{
  imports = [
    ./Samba
    ./adguard
    ./arm
    ./auto-upgrade
    ./asterisk
    ./phone-config-nginx
    ./borgbackup
    ./determinate-nix
    ./bird-bgp
    ./flakehub-auth
    ./fwupd
    ./github-runner
    ./iprouting
    ./kanidm
    ./keepalived
    ./kvm
    ./letsencrypt
    ./monitoring
    ./nfs
    ./nixcache
    ./nut
    ./oauth2-proxy
    ./openssh
    ./printing
    ./rack-shutdown
    ./remotebuilds
    ./reverse-proxy
    ./ser2net
    ./socat
    ./tailscale
    ./talos
    ./tftpd
    ./vsftpd
    ./zfs
  ];
}
