import os

def summarize_content(content, filename):
    """
    Basic summarizer: returns the first non-empty line or a generic message.
    Replace this with an LLM/API call for smarter summaries.
    """
    lines = [line.rstrip() for line in content.splitlines()]
    # Look for a '# Summary:' header in comments
    for line in lines:
        if line.strip().startswith("# Summary:"):
            return line.strip("# ").replace("Summary:", "").strip()
    # Try to extract leading comment block (e.g., for Nix, Python, shell)
    comment_lines = []
    for line in lines:
        if line.strip().startswith("#"):
            comment_lines.append(line.strip("# ").rstrip())
        elif comment_lines:
            break  # Stop at first non-comment after a comment block
    if comment_lines:
        return " ".join(comment_lines)
    # Fallback: show first 5 non-empty lines
    snippet = "\n".join([l for l in lines if l.strip()][:5])
    return snippet if snippet else f"No content to summarize in {filename}."

import datetime

def generate_readme_for_folder(folder):
    files = [f for f in os.listdir(folder) if os.path.isfile(os.path.join(folder, f)) and f != 'readme-doc.md']
    readme_path = os.path.join(folder, 'readme-doc.md')
    with open(readme_path, 'w') as readme:
        # Add a timestamp to force a change
        timestamp = datetime.datetime.utcnow().isoformat() + 'Z'
        readme.write(f"<!-- Autogenerated: {timestamp} -->\n")
        readme.write(f"# {os.path.basename(folder)}\n\n")
        readme.write("## Files\n\n")
        for f in files:
            readme.write(f"- {f}\n")
        readme.write("\n## File Summaries\n\n")
        for f in files:
            file_path = os.path.join(folder, f)
            try:
                with open(file_path, 'r', encoding='utf-8', errors='replace') as file:
                    content = file.read()
                summary = summarize_content(content, f)
            except Exception as e:
                summary = f"Could not read file: {e}"
            readme.write(f"### {f}\n{summary}\n\n")
        # Folder overview: join summaries for a high-level overview
        readme.write("## Overview\n\n")
        if files:
            readme.write("This folder contains the following files with their respective purposes summarized above.\n")
        else:
            readme.write("This folder is currently empty.\n")

def main():
    # Always walk from repo root, even if run from a subfolder
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
    for root, dirs, files in os.walk(repo_root, topdown=True):
        # Skip .git, .github, and hidden folders
        if any(part.startswith('.') for part in root.split(os.sep)):
            continue
        generate_readme_for_folder(root)

if __name__ == "__main__":
    main()
