# Make a user key
# mkdir -p ~/.config/sops/age
# age-keygen -o ~/.config/sops/age/keys.txt

# Display the user public key:
# age-keygen -y ~/.config/sops/age/keys.txt

# Make a host key:
# sudo mkdir -p /var/lib/private/sops/age
# sudo age-keygen -o /var/lib/private/sops/age/keys.txt

# Display the host public key:
# sudo age-keygen -y /var/lib/private/sops/age/keys.txt

# Add secrets
# sops secrets/secrets.yaml

# Rekey secrets.yaml after editing recipients in .sops.yaml:
# sops updatekeys secrets/secrets.yaml
keys:
  - &user_xrs444 age1rzatmse76n9mv975gyeydsj9pafl7mz9ndcznlc2zfwnl7g8x5pqv5haqt
  - &host_xsvr1 age1xhkk62xyufr3a222epq0kfes9yffxyplme8sjfgv6fjes6xdvgjspkwske
  - &host_xsvr2 age1lyv34gqknhrpwy5c0e64hcumfkkacxf2vhmqtuf2r5fgv7x2wyhs943evx
  - &host_xsvr3 age1sud7hw2gdteg8u3fru6sc5u783w9ll38u5thw3u9yfmpu9xw9udq2vl0ka
  - &host_xts1 age1u8za690m39g80xpfwwj4l3lsfwsyhst6hh9jxw7vn63dtue6c9qs7tu4de
  - &host_xts2 age1ud88p7dps3dyjwcmdcfhx2557maj33xplllq56dz5f6snzr4m4xq8gcg4z
  - &host_xdash1 age1he72de5qaluhcwfx6untmcst8pd95njsxun0ut9csgvetsj6ryuq9cpgwc

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_xrs444
      - *host_xsvr1
      - *host_xsvr2
      - *host_xsvr3
      - *host_xts1
      - *host_xts2
      - *host_xdash1
