# Make a user key
# mkdir -p ~/.config/sops/age
# age-keygen -o ~/.config/sops/age/keys.txt

# Display the user public key:
# age-keygen -y ~/.config/sops/age/keys.txt

# Make a host key:
# sudo mkdir -p /var/lib/private/sops/age
# 

# Display the host public key:
# sudo age-keygen -y /var/lib/private/sops/age/keys.txt

# Add secrets
# sops secrets/secrets.yaml

# Rekey secrets.yaml after editing recipients in .sops.yaml:
# sops updatekeys secrets/secrets.yaml
keys:
  - &user_xrs444 age1rzatmse76n9mv975gyeydsj9pafl7mz9ndcznlc2zfwnl7g8x5pqv5haqt
  - &user_builder age1k0pvf8gqe6cfvsa46y5sdyr5sl8t2gctcyuzt8e3hy7dv40alywsvctjmd
  - &host_xsvr1 age15d2cl7x6uu9nrdh2p5kwqdy93e2jtmq0num003z72che6k2sh35sgfxgcf
  - &host_xsvr2 age1vvlmexpuzeyzrh5g6kau8m4du4pxtqnd9fcmsfw7kqyp27afquvqmszlh3
  - &host_xsvr3 age12kpf7eej0xhptqlzg7y7wvx2a2reasvjm44wn3laytazddpy5v4sn4q8z4
  - &host_xts1 age1u8za690m39g80xpfwwj4l3lsfwsyhst6hh9jxw7vn63dtue6c9qs7tu4de
  - &host_xts2 age1ud88p7dps3dyjwcmdcfhx2557maj33xplllq56dz5f6snzr4m4xq8gcg4z
  - &host_xdash1 age1he72de5qaluhcwfx6untmcst8pd95njsxun0ut9csgvetsj6ryuq9cpgwc
  - &host_xhac_radio age16zvw2jkfjcsxkv56anz5hsfmc5p0qy6qeyyeqeg3hm86axvjcpyqxnahqj
  - &host_xlt1-t-vnixos age1fyew76ywr5zyhm4vs670g2g5mzel49k20p25dyexs3x22x2kl4rqxj3urm
  - &host_xlt1-t age1rzatmse76n9mv975gyeydsj9pafl7mz9ndcznlc2zfwnl7g8x5pqv5haqt
  - &host_xlabmgmt age1khgdesh65739s5pvtsq5k38u9wnjys0f668c6ydrx86647lus54qap0mda
  - &host_xlt2-s age16yu4jhkj0q88hmfpn5dhl8y8wjawa4wjx5zaktpmvduadcmwmgxqd9z0ps
  - &host_xdt2-g age1y6zaftf5unztga8fw7qwl9w0n5hkeca8m25fagqckavnmla4pg8sm6grqz
  - &host-xdt3-r age1c284tt2erjny8g8s3u4gp8h9f2x3rhzf7j6fuwlz4704uwdnhv5s3zl9zq
  - &host_xdt1-t age1d37vp633y9s820ew4e3az46yacwnuued0v8mt2xm54ym283fas2qdye8fh
  - &host_xcomm1 age175yqu6xcd764aunprsaxsgyjk80crvvfh2et0qtkua39unsahu4qwmvvn0

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_xrs444
      - *user_builder
      - *host_xsvr1
      - *host_xsvr2
      - *host_xsvr3
      - *host_xts1
      - *host_xts2
      - *host_xdash1
      - *host_xhac_radio
      - *host_xlt1-t-vnixos
      - *host_xlt1-t
      - *host_xlabmgmt
      - *host_xlt2-s
      - *host_xdt2-g
      - *host-xdt3-r
      - *host_xdt1-t
      - *host_xcomm1


