#!/usr/bin/env bash

# Using this to built the ZFS array for now, then mount in boot.nix
# One day I'll do it in Disko, but I need to actually make some progress!
# This method is safer, as it won't fire unless specifically called. I'll migrate it over later.

# Disks involved and VDEV assignments. 

# ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M0SFFNHR - VDEV 1 - 1
# ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M6KTNFY8 - VDEV 1 - 2
# ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M6LCUE2S - VDEV 2 - 1
# ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M6TCTSTR - VDEV 2 - 2

zpool create -f \
      -o ashift=12 \
      -m /zfs zpool-xsvr2 raidz2 \
             ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M0SFFNHR \
             ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M6KTNFY8 \
             ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M6LCUE2S \
             ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M6TCTSTR 

zfs set compression=lz4 recordsize=1M xattr=sa acltype=posixacl atime=off zpool-xsvr2


zfs create zpool-xsvr2/media \
    -o recordsize=1M

zfs create zpool-xsvr2/music \
    -o recordsize=1M

zfs create zpool-xsvr2/devicebackups \
    -o recordsize=1M

zfs create zpool-xsvr2/googlebackups \
    -o recordsize=1M

zfs create zpool-xsvr2/systembackups \
    -o recordsize=1M

zfs create zpool-xsvr2/photos \
    -o recordsize=1M

zfs create zpool-xsvr2/vm \
    -o recordsize=1M