name: FlakeChecker

on:
  push:
  schedule:
    # l33t o'clock
    - cron: '37 13 * * *'
  workflow_dispatch:

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          determinate: true
#      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: DeterminateSystems/flake-checker-action@v9
