name: Build servers

on:
  push:
    branches:
      - main
    paths:
      - 'flake.lock'
  workflow_dispatch:

jobs:
  build-host:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - xsvr1
          - xsvr2
          - xsvr3 
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v16
      with:
        determinate: true
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - name: Building ${{ matrix.host }}
      run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel -L
