---
name: renovate

"on":
  schedule:
    - cron: "0 6 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: renovatebot/github-action@v46.1.17
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: xrs444/nix
